### ISSUE TITLE
Is there any retry mechanism for items that haven't been marked done?

### ISSUE THREAD

**Issue by tomekit** [litements/litequeue#1]
Firstly, thank you very much for making this open source project.

I was wondering if there is any retry mechanism for items that haven't been marked `done` explicitly?

If you pop item, then this happen:
`UPDATE Queue SET status = 1, lock_time = strftime('%s','now') WHERE message_id = ? and status =0`

When you mark item as `done` then this happen:
`UPDATE Queue SET status = 2,  done_time = strftime('%s','now') WHERE message_id = ?`

... but if the queue worker fails and doesn't mark item `done`, what happens next? Would the item with `status=1` stay forever in the queue?

**Comment by polyrand** [comment]
> I was wondering if there is any retry mechanism for items that haven't been marked done explicitly?

There's not, my idea with this was only creating a "foundational" library. The retry mechanism could be implemented as a separate function (maybe running on a thread)

> but if the queue worker fails and doesn't mark item done, what happens next? Would the item with status=1 stay forever in the queue?

That's a good question. If you were using Postgres, you could use something like [`SELECT ... FOR UPDATE`](https://www.postgresql.org/docs/current/sql-select.html#SQL-FOR-UPDATE-SHARE). In that case, if the worker fails, the lock should be released, but now the question is, what happened before the failure? For example, maybe an email has already been sent, but the worker failed before marking the job as `done`.

Now that I think of it, I should implement a method like `.failed(message_id: str)` to reset the status to `0`, that way you would be able to do:

```py
from litequeue import SQLQueue

q = SQLQueue(":memory:")
q.put("hello")

task = q.pop()

try:
    do_work(task["message"])
    q.done(task["message_id"])
except Exception:
    q.failed(taks["message_id"])
```

I will implement this for the next release!

In case there's a failure and the job stays forever with `status=1` in the queue, my thinking was that people could implement a separate worker to clean up jobs, for example (I haven't tried running this code):

```py
from threading import Thread
from litequeue import SQLQueue

q = SQLQueue(":memory:")


def clean_stalled_jobs(queue: SQLQueue, threshold_seconds: int):
    while True:
        stalled_jobs = queue.conn.execute(
            "SELECT * FROM Queue WHERE status = 1 and strftime('%s','now') - lock_time > :threshold",
            (threshold_seconds,),
        ).fetchall()
        for job in stalled_jobs:
            ...
            # remove, set status back to 0, something else...


# 300 seconds = 5 minutes
threshold_seconds = 300
t = Thread(target=clean_stalled_jobs, args=(q, threshold_seconds), daemon=True)
t.start()
```

I'll make sure to add this to the documentation.

Thanks for the question!

**Comment by tomekit** [comment]
Thanks for the update. I think it's also good to have a distinction between failed permanently or failed with retry being expected. I am actually looking at semantics of: `androidx.work.ListenableWorker.Result` (which may or may not be relevant), where `failed()` means permanent failure and `retry()` means failed, but retrying.

Speaking of `clean_stalled_jobs`, I think it would do. I guess instead of SELECT then update query, it can be done in one go: 
`UPDATE Queue SET status = 0, lock_time = null WHERE status = 1 and lock_time...`. 
I think simple atomic queries are always preferable in queue environments which are often used in async environments.

In general: `clean_stalled_jobs`, kind of replicates behavior of AWS SQS visibility timeout. Pretty useful to have task automatically come back for processing.

**Comment by prabirshrestha** [comment]
I’m also interested in this feature. Having only failed() wouldn’t be enough as quitting the process may never call failed method.

Visibility timeout with explicit ack (success) or nack (failed) for popped message would solve the issue. If we don’t ack the message within the timeout, it should show up again.

**Comment by tomekit** [comment]
This is what worked for me:
```
fun moveStuckPendingToExecutable() {
        val db = this.writableDatabase
        db.execSQL("UPDATE Queue SET status = 0, lock_time = null, done_time = null WHERE status = 1 and lock_time < strftime('%s','now', '-1 minute')")

        val cursor = db.rawQuery("select changes()", null)
        cursor.moveToFirst()
        val matchedRows = cursor.getInt(0)
        cursor.close()
        if (matchedRows > 0) {
            Log.i(Constants.APP_LOG_TAG, "moveStuckPendingToExecutable, matchedRows: $matchedRows")
        }
    }
```

**Comment by polyrand** [comment]
Hi, sorry for the late response, I'm not having much spare time lately, and I have also invested more time on [litexplore](https://github.com/litements/litexplore).

I will eventually look into better failure handling. On the other hand, anyone can inherit from [the main `SQLQueue` class](https://github.com/litements/litequeue/blob/8d1663ab807fa4843725ae21cb916b2cb284d771/litequeue.py#L25) to extend the functionality. Something like:


```py
from litequeue import SQLQueue

class CustomLiteQueue(SQLQueue):
    def __init__(self, ...):
        super().__init__(...)
        ...

    def failed(self, threshold_seconds):
        return self.conn.execute(
            "SELECT * FROM Queue WHERE status = 1 and strftime('%s','now') - lock_time > :threshold",
            (threshold_seconds,),
        ).fetchall()

    def reset_failed(self, threshold_seconds):
        self.conn.execute(
            "UPDATE Queue SET status = 0, lock_time = null, done_time = null WHERE status = 1 and strftime('%s','now') - lock_time > :threshold",
            (threshold_seconds,),
        )
```

Now you can use `CustomliteQueue` as a substitute of `SQLQueue`.

**Comment by polyrand** [comment]
I've now released a new version that, among other changes, includes a few new methods:

`.mark_failed(message_id: str)`: Mark a message as failed
`.retry(message_id: str)`: Mark a failed message as "ready" again
`.list_locked(threshold_seconds: int)`: List all the messages that have been locked for more than `threshold_seconds`.


With this, I'm including all the necessary primitives that I'm planning for `litequeue`, extra functionality can be built on top, but probably won't be part of the module itself. For example, you can run a subprocess that checks `.list_locked()` every few seconds and then runs `.mark_failed()` according to some logic. But all of that should be implemented by the user, not this package.

Important notice, now I'm measuring the time using [nanoseconds](https://docs.python.org/3/library/time.html#time.time_ns), and I've stopped using the SQLite function `strftime('%s','now')`. I'm mentioning it because I was using the `strftime('%s','now')` functions in some of the examples I posted here. The message IDs are now UUIDv7 strings, not random hexadecimal blobs.
