### ISSUE TITLE
Question: Can this be used across processes?

### ISSUE THREAD

**Issue by Jwink3101** [litements/litequeue#5]
I read the source code and I think using `EXCLUSIVE` transactions, the answer is affirmative, but can I have one Python process running that adds to the queue then multiple others reading and working? It would have to rely on sqlite's locking but I think the transaction does that.

**Comment by polyrand** [comment]
Hi!

Yes, this can be used across processes. The task you describe is actually one of the use cases I had in mind when writing this (multiple consumer processes using the same DB). You can have multiple processes using the same underlying queue/database to add and retrieve messages. All the "locking" is handled internally by SQLite.

**Comment by Jwink3101** [comment]
Great! Thanks
