### ISSUE TITLE
lastrowid always returns 0 causing AssertionError

### ISSUE THREAD

**Issue by eduntct** [litements/litequeue#6]
When calling _done()_,  _lastrowid_ always evaluates to 0, which causes "assert x" to raise an AssertionError exception.

This is happening using Python 3.10.12 and sqlite3 3.42.0

https://github.com/litements/litequeue/blob/156177d6eca8934a2251a28d88fce054e1bf9453/litequeue.py#L379

**Comment by polyrand** [comment]
Thanks for the report! I have removed the assertion, it wasn't very useful anyway (I don't think getting the `rowid` of the last "done" message provides more than what you already get using the `message_id` attribute).

I have pushed version 0.7, which should fix this (and another bug I found when using more recent Python versions).

**Comment by polyrand** [comment]
Closed by 1bdf02e03001db62a5ed1c06bdf56d4076a44d20
